source 'https://rubygems.org'
ruby '2.3.0'
gem 'rails', '4.2.5.2'

# Rails defaults
gem 'sqlite3'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'byebug'
gem 'web-console', '~> 2.0'
gem 'spring'
# extra gems
gem 'foundation-rails', '~> 5.5'
gem 'gibbon'
gem 'high_voltage'
gem 'simple_form'
group :development do
  gem 'better_errors'
  gem 'quiet_assets'
  gem 'rails_layout'
end

=begin
	
	desc of "extra" gems we are learning about"
Here are gems we’ll add to the Gemfile:

foundation-rails - front-end framework
gibbon - access to the MailChimp API
high_voltage - for static pages like “about”
simple_form - forms made easy
We’ll also add utilities that make development easier:

better_errors - helps when things go wrong
quiet_assets - suppresses distracting messages in the log
rails_layout - generates files for an application layout
=end